# Project: 8-2
# Makefile created by Dev-C++ 5.9.2

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = 8-2.o
LINKOBJ  = 8-2.o
LIBS     = -L"D:/Documents/Tencent Files/1533003633/FileRecv/Dev-Cpp/MinGW64/lib" -L"D:/Documents/Tencent Files/1533003633/FileRecv/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/Documents/Tencent Files/1533003633/FileRecv/Dev-Cpp/MinGW64/include" -I"D:/Documents/Tencent Files/1533003633/FileRecv/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Documents/Tencent Files/1533003633/FileRecv/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include"
CXXINCS  = -I"D:/Documents/Tencent Files/1533003633/FileRecv/Dev-Cpp/MinGW64/include" -I"D:/Documents/Tencent Files/1533003633/FileRecv/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Documents/Tencent Files/1533003633/FileRecv/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"D:/Documents/Tencent Files/1533003633/FileRecv/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++"
BIN      = 8-2.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

8-2.o: 8-2.cpp
	$(CPP) -c 8-2.cpp -o 8-2.o $(CXXFLAGS)
